# This is a basic workflow to help you get started with Actions

name: dotTEST TIA

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dotTEST-TIA:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Depth set to 0 for highest performance
      - name: Checkout sources
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      # Download last artifacts and unzip them
      - uses: blablacar/action-download-last-artifact@master
        with:
         name: Test Report files
         path: baseline_reports

      - name: Run dotTEST TIA
        id: dottest_ut
        # You may pin to the exact commit or the version.
        # uses: tobyash86/run-dottest-analyzer-proto@1bc4be095189f455793afdb10b47127e06ae25ff
        uses: parasoft/run-dottest-analyzer@2.0.0
        with:
          # Path to working directory.
          installDir: c:\Program Files\Parasoft\dotTEST\2022.2
          testConfig: Run VSTest Tests with Coverage
          referenceReportFile: c:\actions-runner\_work\WebGoat.NET\WebGoat.NET\baseline_reports\report.xml
          referenceCoverageFile: c:\actions-runner\_work\WebGoat.NET\WebGoat.NET\baseline_reports\coverage.xml
      
      # ---------------------------------------------------------------
      # Upload the findings into the GitHub code scanning alert section
      - name: Upload TIA results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.dottest_ut.outputs.report }}
          
      # ---------------------------------------------------------------
      # Archive the findings reports as job artifact
      - name: Upload execution artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TIA Report files
          path: ${{ steps.dottest_ut.outputs.reportDir }}/*.*

